/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Thu Oct 31 13:22:37 MSK 2013 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"NDMS"
#define OS_VERSION		"NDMS/1.00"
#define OS_URL			"http://www.zyxel.ru/"

/* full path of the file database */
#define DEFAULT_DB_PATH		"/media/DISK_A1/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/media/DISK_A1/minidlna"

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
#define USE_DAEMON

/* Enable if the system inotify.h exists.  Otherwise our own inotify.h will be used. */
#define HAVE_INOTIFY

/* Enable if the system iconv.h or nconv.h exists.  ID3 tag reading in various character sets will not work properly otherwise. */
#define HAVE_NCONV_H
/*#define HAVE_ICONV_H*/

/*#define ENABLE_NLS*/

/* Enable NETGEAR-specific tweaks. */
/*#define NETGEAR*/
/* Enable ReadyNAS-specific tweaks. */
/*#define READYNAS*/
/* Compile in TiVo support. */
/*#define TIVO_SUPPORT*/
/* Enable PnPX support. */
/*#define PNPX 0 */

#endif
