/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Thu Oct 31 13:22:37 MSK 2013 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"NDMS"
#define OS_VERSION		"NDMS/1.00"
#define OS_URL			"http://www.zyxel.ru/"

#define HAVE_AVUTIL_H
#define HAVE_AVCODEC_H
#define HAVE_AVFORMAT_H

#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_GETTIME_SYSCALL 1
#define HAVE_INOTIFY 1
#define HAVE_LINUX_SENDFILE_API 1
#define HAVE_SQLITE3_MALLOC 1
#define HAVE_SQLITE3_PREPARE_V2 1

/* full path of the file database */
#define DEFAULT_DB_PATH		"/tmp/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/tmp/minidlna"

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
#define USE_DAEMON

/* Enable if the system inotify.h exists.  Otherwise our own inotify.h will be used. */
#define HAVE_INOTIFY_H

/* Enable if the system iconv.h exists.  ID3 tag reading in various character sets will not work properly otherwise. */
/* #define HAVE_ICONV_H */

/* Enable if the system libintl.h exists for NLS support. */
/* #define ENABLE_NLS */

/* Enable NETGEAR-specific tweaks. */
/*#define NETGEAR*/
/* Enable ReadyNAS-specific tweaks. */
/*#define READYNAS*/
/* Compile in TiVo support. */
#define TIVO_SUPPORT
/* Enable PnPX support. */
#define PNPX 0

#endif
